# Use an official Python runtime as a base image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Install dependencies
COPY backend/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Django backend code into the container
COPY backend/ /app/

# Run the "runmqtt" command with Django's manage.py script
CMD ["python", "manage.py", "runmqtt"]  # Updated this line

# Expose the Django development server port
EXPOSE 8000
