version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=wirepas
      - POSTGRES_USER=wirepas
      - POSTGRES_PASSWORD=admin
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MQTT_USERNAME='groupe1'
      - MQTT_PASSWORD='T18oCz84diyh'
      - DATABASE_URL=postgres://dbuser:dbpass@db/dbname
    depends_on:
      - frontend
      - db
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app