# Generated by Django 4.2.2 on 2023-07-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('115', 'Movement'), ('136', 'ADC'), ('112', 'Temperature'), ('114', 'Humidity'), ('116', 'Atmospheric Pressure'), ('118', 'Luminosity'), ('119', 'Sound'), ('128', 'Voltage'), ('131', 'CO2'), ('100', 'Passage'), ('101', 'Heater'), ('102', 'AC'), ('103', 'Vent'), ('104', 'Light')], max_length=200, null=True),
        ),
    ]
