# Generated by Django 4.2.2 on 2023-07-18 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sensor_sensor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
