# Generated by Django 4.2.2 on 2023-07-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_automationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='node',
            field=models.UUIDField(default='e3e3e3e3-e3e3-e3e3-e3e3-e3e3e3e3e3e3'),
            preserve_default=False,
        ),
    ]
