# Generated by Django 4.2.2 on 2023-07-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sensor_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='node',
            new_name='source_address',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='source_address',
        ),
    ]
